services:
  - type: web
    name: vettix-app-id
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: vettix-db
          property: connectionString
      - key: APP_KEY
        sync: false # You will be prompted to enter this in the Render dashboard during setup

databases:
  - name: vettix-db
    databaseName: vettix_db
    user: wad_user
    plan: free
